---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R mail $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp cgi-bin.zip $DEPLOYPATH
    - /bin/cp gulpfile.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
